debug: false

logging:
  level:
    com.noldaga: debug
    org.springframework:
      data: debug
      web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/noldaga?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: noldaga
    password: noldaga
    driver-class-name: com.mysql.cj.jdbc.Driver
     # urL: jdbc:h2:mem:testdb;mode=mysql
     # driver-class-name: org.h2.Driver

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always

  h2:
    console:
      enabled: true


jwt:
  secret-key: this-Key-Is-Over-32Bytes-For-HmacShaKey
  #30days
  token.expired-time-ms: 2592000000


com:
  noldaga:
    upload:
      path: C:\\upload